### ISSUE TITLE
Feature Request - Part2B support

### ISSUE THREAD

**Issue by cdgriffith** [LBeaudoux/iso639#2]
Thank you for this great lightweight library! It's very nice to have one that is open licensed, unlike [iso-639](https://pypi.org/project/iso-639/)'s restrictive AGPL. 

I am integrating this into a program that uses FFmpeg, which relies on `Part2B` support (languages like French would break currently looking for "fre") and would be nice to have that as part of your library natively. 

I understand that would complicate it and probably require either a flag or lookup on initialization, and might be outside what you want to do with the library, just a suggestion!

**Comment by LBeaudoux** [comment]
`part2B` and `part2T` language codes are now supported by the latest version available on PyPI. I think it should suit your requirements.

Thank you for your interest in this library!
