### ISSUE TITLE
Test fail (ISO-639-2_utf-8.txt not installed in build directory)

### ISSUE THREAD

**Issue by marillat** [LBeaudoux/iso639#22]
Hi,
Debian unstable python 3.12.6 Debian unstable amd64

I can fix that from the debian/rules, but it(s not really clean
```
 mkdir -p .pybuild/cpython3_3.12_iso639/build/dev_iso639/downloads/
 cp dev_iso639/downloads/ISO-639-2_utf-8.txt .pybuild/cpython3_3.12_iso639/build/dev_iso639/downloads/
```
Error messages
```
I: pybuild base:311: cd /build/iso639-dmo-2.4.1/.pybuild/cpython3_3.12_iso639/build; python3.12 -m pytest tests
============================= test session starts ==============================
platform linux -- Python 3.12.6, pytest-8.3.3, pluggy-1.5.0
rootdir: /build/iso639-dmo-2.4.1/.pybuild/cpython3_3.12_iso639/build
configfile: pyproject.toml
plugins: typeguard-4.3.0
collected 0 items / 1 error

==================================== ERRORS ====================================
____________________ ERROR collecting tests/test_iso639.py _____________________
tests/test_iso639.py:21: in <module>
    class TestLang:
tests/test_iso639.py:117: in TestLang
    get_iso6392_rows(),
tests/utils.py:8: in get_iso6392_rows
    with open(DOWNLOAD_DIR + "ISO-639-2_utf-8.txt", encoding="utf-8-sig") as f:
E   FileNotFoundError: [Errno 2] No such file or directory: 'dev_iso639/downloads/ISO-639-2_utf-8.txt'
=========================== short test summary info ============================
ERROR tests/test_iso639.py - FileNotFoundError: [Errno 2] No such file or dir...
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.12s ===============================
```

**Comment by marillat** [comment]
I noticed that the ISO-639-2_utf-8.txt is installed in the package.
It's really necessary ? 
```
/usr/lib/python3/dist-packages/
/usr/lib/python3/dist-packages/dev_iso639/
/usr/lib/python3/dist-packages/dev_iso639/downloads/
/usr/lib/python3/dist-packages/dev_iso639/downloads/ISO-639-2_utf-8.txt
```

**Comment by LBeaudoux** [comment]
> I noticed that the ISO-639-2_utf-8.txt is installed in the package. It's really necessary ?

I guess not. Only the JSON mappings in `iso639/data`.are loaded into memory and read by the `iso639.Lang` class.

The files in `dev_iso639/downloads/` were downloaded from the websites of the ISO 639 registration authorities. These original files were used to generate the JSON mappings embedded in `iso639/data`. They are also read during tests to check that the values returned by the `iso639.Lang` class systematically match those in the official ISO 639 tables.

As indicated at the end of [`pyproject.toml`](https://github.com/LBeaudoux/iso639/blob/master/pyproject.toml), only the `iso639` and `iso639/data` directories are supposed to be copied during packaging. This could explain why your tests initially failed after you built your package with pybuild.

I created this test suite to help me during development. I didn't anticipate that some users would build the package from source and then test it with no access to the original data files. One solution might be to have only basic tests that don't require any additional data file in `tests/` and move the current test suite into a new `dev_tests/` directory. 

But maybe you have a better idea to suggest?

**Comment by LBeaudoux** [comment]
I have created a [branch](https://github.com/LBeaudoux/iso639/tree/fix-pybuild-tests) for this issue. Could you please build your package from it and let me know if your problem persists?

**Comment by marillat** [comment]
Well done. This code fix this issue.

Many thanks.
