### ISSUE TITLE
paired list

### ISSUE THREAD

**Issue by AtomicNess123** [LBeaudoux/iso639#9]
How to get a paired list of language and iso codes from the package? Thanks.

**Comment by LBeaudoux** [comment]
Sorry but this package does not aim at listing language code mappings. That said,  you can still probably generate the data your are looking for from `Lang._data`:
```python
>>> from iso639 import Lang
>>> [(d["name"], pt3) for pt3, d in Lang._data["pt3"].items()]
[('Ghotuo', 'aaa'), ('Alumu-Tesu', 'aab'), ... , ('Zaza', 'zza'), ('Zuojiang Zhuang', 'zzj')]
```

**Comment by AtomicNess123** [comment]
Thanks so much. These are three letter codes. Are there also two letter codes (eg., EN, RU, FR)?

**Comment by LBeaudoux** [comment]
Just replace `pt3` by` pt1`:
```python
>>> [(d["name"], pt1) for pt1, d in Lang._data["pt1"].items()]
[('Afar', 'aa'), ('Abkhazian', 'ab'),  ... , ('Chinese', 'zh'), ('Zulu', 'zu')]
```

**Comment by AtomicNess123** [comment]
Silly me, thanks!

**Comment by LBeaudoux** [comment]
Since v2.0, you can now iterate more easily and efficiently through all possible `Lang` instances with `iter_langs`:
```python
>>> from iso639 import iter_langs
>>> [(lang.name, lang.pt3) for lang in iter_langs() if lang.pt3]
[("'Are'are", 'alu'), ("'Auhelawa", 'kud'), ... , ('ǂUngkue', 'gku'), ('ǃXóõ', 'nmn')]
```
